// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/domain/commanddata/certificate.proto

package commanddata

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _certificate_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RequestCertificate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RequestCertificate) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RequestCertificate with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RequestCertificateMultiError, or nil if none found.
func (m *RequestCertificate) ValidateAll() error {
	return m.validate(true)
}

func (m *RequestCertificate) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetReferencedAggregateId()); err != nil {
		err = RequestCertificateValidationError{
			field:  "ReferencedAggregateId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(m.GetReferencedAggregateType()) > 60 {
		err := RequestCertificateValidationError{
			field:  "ReferencedAggregateType",
			reason: "value length must be at most 60 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RequestCertificate_ReferencedAggregateType_Pattern.MatchString(m.GetReferencedAggregateType()) {
		err := RequestCertificateValidationError{
			field:  "ReferencedAggregateType",
			reason: "value does not match regex pattern \"^[a-zA-Z][A-Za-z0-9_-]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !bytes.HasPrefix(m.GetSigningRequest(), []uint8{0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x43, 0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x20, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D}) {
		err := RequestCertificateValidationError{
			field:  "SigningRequest",
			reason: "value does not have prefix \"\\x2D\\x2D\\x2D\\x2D\\x2D\\x42\\x45\\x47\\x49\\x4E\\x20\\x43\\x45\\x52\\x54\\x49\\x46\\x49\\x43\\x41\\x54\\x45\\x20\\x52\\x45\\x51\\x55\\x45\\x53\\x54\\x2D\\x2D\\x2D\\x2D\\x2D\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !bytes.HasSuffix(m.GetSigningRequest(), []uint8{0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x43, 0x45, 0x52, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x45, 0x20, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D}) {
		err := RequestCertificateValidationError{
			field:  "SigningRequest",
			reason: "value does not have suffix \"\\x2D\\x2D\\x2D\\x2D\\x2D\\x45\\x4E\\x44\\x20\\x43\\x45\\x52\\x54\\x49\\x46\\x49\\x43\\x41\\x54\\x45\\x20\\x52\\x45\\x51\\x55\\x45\\x53\\x54\\x2D\\x2D\\x2D\\x2D\\x2D\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RequestCertificateMultiError(errors)
	}
	return nil
}

func (m *RequestCertificate) _validateUuid(uuid string) error {
	if matched := _certificate_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RequestCertificateMultiError is an error wrapping multiple validation errors
// returned by RequestCertificate.ValidateAll() if the designated constraints
// aren't met.
type RequestCertificateMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RequestCertificateMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RequestCertificateMultiError) AllErrors() []error { return m }

// RequestCertificateValidationError is the validation error returned by
// RequestCertificate.Validate if the designated constraints aren't met.
type RequestCertificateValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RequestCertificateValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RequestCertificateValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RequestCertificateValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RequestCertificateValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RequestCertificateValidationError) ErrorName() string {
	return "RequestCertificateValidationError"
}

// Error satisfies the builtin error interface
func (e RequestCertificateValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRequestCertificate.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RequestCertificateValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RequestCertificateValidationError{}

var _RequestCertificate_ReferencedAggregateType_Pattern = regexp.MustCompile("^[a-zA-Z][A-Za-z0-9_-]+$")
