// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/domain/commanddata/user.proto

package commanddata

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateUserCommandData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateUserCommandData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserCommandData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateUserCommandDataMultiError, or nil if none found.
func (m *CreateUserCommandData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserCommandData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	// no validation rules for Name

	if len(errors) > 0 {
		return CreateUserCommandDataMultiError(errors)
	}
	return nil
}

// CreateUserCommandDataMultiError is an error wrapping multiple validation
// errors returned by CreateUserCommandData.ValidateAll() if the designated
// constraints aren't met.
type CreateUserCommandDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserCommandDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserCommandDataMultiError) AllErrors() []error { return m }

// CreateUserCommandDataValidationError is the validation error returned by
// CreateUserCommandData.Validate if the designated constraints aren't met.
type CreateUserCommandDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserCommandDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserCommandDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserCommandDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserCommandDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserCommandDataValidationError) ErrorName() string {
	return "CreateUserCommandDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserCommandDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserCommandData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserCommandDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserCommandDataValidationError{}

// Validate checks the field values on CreateUserRoleBindingCommandData with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CreateUserRoleBindingCommandData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateUserRoleBindingCommandData with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateUserRoleBindingCommandDataMultiError, or nil if none found.
func (m *CreateUserRoleBindingCommandData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateUserRoleBindingCommandData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Role

	// no validation rules for Scope

	// no validation rules for Resource

	if len(errors) > 0 {
		return CreateUserRoleBindingCommandDataMultiError(errors)
	}
	return nil
}

// CreateUserRoleBindingCommandDataMultiError is an error wrapping multiple
// validation errors returned by
// CreateUserRoleBindingCommandData.ValidateAll() if the designated
// constraints aren't met.
type CreateUserRoleBindingCommandDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateUserRoleBindingCommandDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateUserRoleBindingCommandDataMultiError) AllErrors() []error { return m }

// CreateUserRoleBindingCommandDataValidationError is the validation error
// returned by CreateUserRoleBindingCommandData.Validate if the designated
// constraints aren't met.
type CreateUserRoleBindingCommandDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateUserRoleBindingCommandDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateUserRoleBindingCommandDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateUserRoleBindingCommandDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateUserRoleBindingCommandDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateUserRoleBindingCommandDataValidationError) ErrorName() string {
	return "CreateUserRoleBindingCommandDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreateUserRoleBindingCommandDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateUserRoleBindingCommandData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateUserRoleBindingCommandDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateUserRoleBindingCommandDataValidationError{}
