// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/domain/projections/metadata.proto

package projections

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on LifecycleMetadata with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LifecycleMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LifecycleMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LifecycleMetadataMultiError, or nil if none found.
func (m *LifecycleMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *LifecycleMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCreated()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "Created",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "Created",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LifecycleMetadataValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedById

	if all {
		switch v := interface{}(m.GetLastModified()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "LastModified",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastModified()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LifecycleMetadataValidationError{
				field:  "LastModified",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for LastModifiedById

	// no validation rules for DeletedById

	if all {
		switch v := interface{}(m.GetDeleted()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "Deleted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LifecycleMetadataValidationError{
					field:  "Deleted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeleted()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LifecycleMetadataValidationError{
				field:  "Deleted",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LifecycleMetadataMultiError(errors)
	}

	return nil
}

// LifecycleMetadataMultiError is an error wrapping multiple validation errors
// returned by LifecycleMetadata.ValidateAll() if the designated constraints
// aren't met.
type LifecycleMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LifecycleMetadataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LifecycleMetadataMultiError) AllErrors() []error { return m }

// LifecycleMetadataValidationError is the validation error returned by
// LifecycleMetadata.Validate if the designated constraints aren't met.
type LifecycleMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LifecycleMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LifecycleMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LifecycleMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LifecycleMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LifecycleMetadataValidationError) ErrorName() string {
	return "LifecycleMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e LifecycleMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLifecycleMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LifecycleMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LifecycleMetadataValidationError{}
