// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package queryhandler

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// GetAll returns all users.
	GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_GetAllClient, error)
	// GetById returns the user found by the given id.
	GetById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*User, error)
	// GetByEmail returns the user found by the given email address.
	GetByEmail(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*User, error)
	// GetRoleBindingsById returns all role bindings related to the given user id.
	GetRoleBindingsById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (UserService_GetRoleBindingsByIdClient, error)
	// GetAuditTrailById returns a stream of all events related to the given id
	GetAuditTrailById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (UserService_GetAuditTrailByIdClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (UserService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/queryhandler.UserService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_GetAllClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type userServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *userServiceGetAllClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) GetById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/queryhandler.UserService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetByEmail(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/queryhandler.UserService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRoleBindingsById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (UserService_GetRoleBindingsByIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/queryhandler.UserService/GetRoleBindingsById", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetRoleBindingsByIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_GetRoleBindingsByIdClient interface {
	Recv() (*UserRoleBinding, error)
	grpc.ClientStream
}

type userServiceGetRoleBindingsByIdClient struct {
	grpc.ClientStream
}

func (x *userServiceGetRoleBindingsByIdClient) Recv() (*UserRoleBinding, error) {
	m := new(UserRoleBinding)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) GetAuditTrailById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (UserService_GetAuditTrailByIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[2], "/queryhandler.UserService/GetAuditTrailById", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceGetAuditTrailByIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_GetAuditTrailByIdClient interface {
	Recv() (*AuditEvent, error)
	grpc.ClientStream
}

type userServiceGetAuditTrailByIdClient struct {
	grpc.ClientStream
}

func (x *userServiceGetAuditTrailByIdClient) Recv() (*AuditEvent, error) {
	m := new(AuditEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// GetAll returns all users.
	GetAll(*empty.Empty, UserService_GetAllServer) error
	// GetById returns the user found by the given id.
	GetById(context.Context, *wrappers.StringValue) (*User, error)
	// GetByEmail returns the user found by the given email address.
	GetByEmail(context.Context, *wrappers.StringValue) (*User, error)
	// GetRoleBindingsById returns all role bindings related to the given user id.
	GetRoleBindingsById(*wrappers.StringValue, UserService_GetRoleBindingsByIdServer) error
	// GetAuditTrailById returns a stream of all events related to the given id
	GetAuditTrailById(*wrappers.StringValue, UserService_GetAuditTrailByIdServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetAll(*empty.Empty, UserService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserServiceServer) GetById(context.Context, *wrappers.StringValue) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserServiceServer) GetByEmail(context.Context, *wrappers.StringValue) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByEmail not implemented")
}
func (UnimplementedUserServiceServer) GetRoleBindingsById(*wrappers.StringValue, UserService_GetRoleBindingsByIdServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRoleBindingsById not implemented")
}
func (UnimplementedUserServiceServer) GetAuditTrailById(*wrappers.StringValue, UserService_GetAuditTrailByIdServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAuditTrailById not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetAll(m, &userServiceGetAllServer{stream})
}

type UserService_GetAllServer interface {
	Send(*User) error
	grpc.ServerStream
}

type userServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *userServiceGetAllServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queryhandler.UserService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetById(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queryhandler.UserService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetByEmail(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRoleBindingsById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrappers.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetRoleBindingsById(m, &userServiceGetRoleBindingsByIdServer{stream})
}

type UserService_GetRoleBindingsByIdServer interface {
	Send(*UserRoleBinding) error
	grpc.ServerStream
}

type userServiceGetRoleBindingsByIdServer struct {
	grpc.ServerStream
}

func (x *userServiceGetRoleBindingsByIdServer) Send(m *UserRoleBinding) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_GetAuditTrailById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrappers.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).GetAuditTrailById(m, &userServiceGetAuditTrailByIdServer{stream})
}

type UserService_GetAuditTrailByIdServer interface {
	Send(*AuditEvent) error
	grpc.ServerStream
}

type userServiceGetAuditTrailByIdServer struct {
	grpc.ServerStream
}

func (x *userServiceGetAuditTrailByIdServer) Send(m *AuditEvent) error {
	return x.ServerStream.SendMsg(m)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queryhandler.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _UserService_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _UserService_GetByEmail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _UserService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRoleBindingsById",
			Handler:       _UserService_GetRoleBindingsById_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAuditTrailById",
			Handler:       _UserService_GetAuditTrailById_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/queryhandler/service.proto",
}

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantServiceClient interface {
	// GetAll returns all tenants.
	GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (TenantService_GetAllClient, error)
	// GetById returns the tenant found by the given id.
	GetById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Tenant, error)
	// GetAuditTrailById returns a stream of all events related to the given id
	GetAuditTrailById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (TenantService_GetAuditTrailByIdClient, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (TenantService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &TenantService_ServiceDesc.Streams[0], "/queryhandler.TenantService/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &tenantServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TenantService_GetAllClient interface {
	Recv() (*Tenant, error)
	grpc.ClientStream
}

type tenantServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *tenantServiceGetAllClient) Recv() (*Tenant, error) {
	m := new(Tenant)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tenantServiceClient) GetById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, "/queryhandler.TenantService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetAuditTrailById(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (TenantService_GetAuditTrailByIdClient, error) {
	stream, err := c.cc.NewStream(ctx, &TenantService_ServiceDesc.Streams[1], "/queryhandler.TenantService/GetAuditTrailById", opts...)
	if err != nil {
		return nil, err
	}
	x := &tenantServiceGetAuditTrailByIdClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TenantService_GetAuditTrailByIdClient interface {
	Recv() (*AuditEvent, error)
	grpc.ClientStream
}

type tenantServiceGetAuditTrailByIdClient struct {
	grpc.ClientStream
}

func (x *tenantServiceGetAuditTrailByIdClient) Recv() (*AuditEvent, error) {
	m := new(AuditEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations must embed UnimplementedTenantServiceServer
// for forward compatibility
type TenantServiceServer interface {
	// GetAll returns all tenants.
	GetAll(*empty.Empty, TenantService_GetAllServer) error
	// GetById returns the tenant found by the given id.
	GetById(context.Context, *wrappers.StringValue) (*Tenant, error)
	// GetAuditTrailById returns a stream of all events related to the given id
	GetAuditTrailById(*wrappers.StringValue, TenantService_GetAuditTrailByIdServer) error
	mustEmbedUnimplementedTenantServiceServer()
}

// UnimplementedTenantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTenantServiceServer struct {
}

func (UnimplementedTenantServiceServer) GetAll(*empty.Empty, TenantService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedTenantServiceServer) GetById(context.Context, *wrappers.StringValue) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedTenantServiceServer) GetAuditTrailById(*wrappers.StringValue, TenantService_GetAuditTrailByIdServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAuditTrailById not implemented")
}
func (UnimplementedTenantServiceServer) mustEmbedUnimplementedTenantServiceServer() {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TenantServiceServer).GetAll(m, &tenantServiceGetAllServer{stream})
}

type TenantService_GetAllServer interface {
	Send(*Tenant) error
	grpc.ServerStream
}

type tenantServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *tenantServiceGetAllServer) Send(m *Tenant) error {
	return x.ServerStream.SendMsg(m)
}

func _TenantService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/queryhandler.TenantService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetById(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetAuditTrailById_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrappers.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TenantServiceServer).GetAuditTrailById(m, &tenantServiceGetAuditTrailByIdServer{stream})
}

type TenantService_GetAuditTrailByIdServer interface {
	Send(*AuditEvent) error
	grpc.ServerStream
}

type tenantServiceGetAuditTrailByIdServer struct {
	grpc.ServerStream
}

func (x *tenantServiceGetAuditTrailByIdServer) Send(m *AuditEvent) error {
	return x.ServerStream.SendMsg(m)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queryhandler.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _TenantService_GetById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _TenantService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAuditTrailById",
			Handler:       _TenantService_GetAuditTrailById_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/queryhandler/service.proto",
}
