repositories:
  - url: https://monoskope.io/test1.git
    branch: main
    subdir: rbac/test
    interval: 5m
    caCert: dGhpcy1pcy1hLWNhLWNlcnQ=
    basicAuthPath: test_repo_one_basic_auth.yaml
    allClusters: true
  - url: https://monoskope.io/test2.git
    branch: test
    interval: 5m
    sshAuthPath: test_repo_two_ssh_auth.yaml
    clusters:
      - "dev"
      - "prod"
mappings:
  - scope: CLUSTER
    role: admin
    clusterRole: cluster-admin
  - scope: TENANT
    role: oncall
    clusterRole: app-oncallee
usernamePrefix: "m8-"
