repositories:
  - url: https://monoskope.io/test1.git
    branch: main
    subdir: rbac/test
    interval: 5m
    caCert: dGhpcy1pcy1hLWNhLWNlcnQ=
    allClusters: true
    auth:
      type: basic
      envPrefix: test1
  - url: https://monoskope.io/test2.git
    branch: test
    interval: 5m
    auth:
      type: ssh
      envPrefix: test2
    clusters:
      - "dev"
      - "prod"
mappings:
  - scope: CLUSTER
    role: admin
    clusterRole: cluster-admin
  - scope: TENANT
    role: oncall
    clusterRole: app-oncallee
usernamePrefix: "m8-"
