sequenceDiagram
    participant U as User
    participant MCTL as monoctl
    participant GW as Gateway
    participant CH as CommandHandler
    participant QH as QueryHandler

    U-->>+MCTL: monoctl create one-time-password
    MCTL-->>+GW: calls CreateOneTimePassword()
    GW-->>-MCTL: returns CreateOneTimePasswordResponse
    MCTL-->>U: Show secret and/or QR Code
    U-->>U: Uses app to enter/scan and create TOTP
    U-->>MCTL: Enters TOTP
