# Dev environment values for monoskope.

name: monoskope
nameOverride: ""
fullnameOverride: ""

pullSecret: ""

dex:
  enabled: true
  config:
    storage:
      type: sqlite3
      config:
        file: examples/dex.db
    staticClients:
      - id: gateway
        secret: "gateway-app-secret"
        name: "Monoskope Gateway"
        redirectURIs:
          - "http://localhost:6555/oauth/callback"
      - id: monoctl
        secret: "monoctl-app-secret"
        name: "Monoskope CLI"
        redirectURIs:
          - "http://localhost:5555/oauth/callback"
    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
