# Local dev environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - gitlab-registry

dex:
  enabled: true
  replicas: 1
  config:
    storage:
      type: sqlite3
      config:
        file: /tmp/dex.db
    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

monoskope-gateway:
  replicaCount: 1
  auth:
    allowRootToken: true

ingress:
  enabled: true

rabbitmq:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: false
  image:
    repository: gitlab.figo.systems/platform/dependency_proxy/containers/bitnami/rabbitmq
    tag: 3.8.9
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
  extraConfiguration: |-
    load_definitions = /app/rabbitmq-definitions.json
  auth:
    username: admin
    password: foo # this will be overwritten by a real password but needs to be set initially
    existingErlangSecret: rabbitmq-erlang-cookie
    tls:
      enabled: true
      existingSecret: rabbitmq-leaf
  podAnnotations:
    linkerd.io/inject: disabled
