# Local dev environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - name: gitlab-registry

gateway:
  enabled: false

eventstore:
  enabled: false

ingress:
  enabled: true

commandhandler:
  enabled: false

queryhandler:
  enabled: false

rabbitmq:
  enabled: false
  replicaCount: 3
  persistence:
    enabled: false
  image:
    repository: gitlab.figo.systems/platform/dependency_proxy/containers/bitnami/rabbitmq
    tag: 3.8.9
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
  extraConfiguration: |-
    load_definitions = /app/rabbitmq-definitions.json
  auth:
    username: admin
    password: foo # this will be overwritten by a real password but needs to be set initially
    existingErlangSecret: rabbitmq-erlang-cookie
    tls:
      enabled: true
      existingSecret: rabbitmq-leaf
  podAnnotations:
    linkerd.io/inject: disabled

cockroachdb:
  enabled: false

ambassador:
  replicaCount: 1
