# Dev environment values for monoskope.

name: monoskope
nameOverride: ""
fullnameOverride: ""

dex:
  enabled: true
  config:
    storage:
      type: sqlite3
      config:
        file: /tmp/dex.db
    enablePasswordDB: true
    staticPasswords:
      - email: "admin@example.com"
        # bcrypt hash of the string "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

gateway:
  auth:
    allowRootToken: true
  pullSecret: gitlab-registry

ingress:
  enabled: true
