# Dev cluster environment values for monoskope.

imageTag: &imageTag "0.0.1-local"

vaultOperator:
  enabled: true
  basePath: app/{{ .Release.Namespace }}

hosting:
  issuer: letsencrypt
  domain: monoskope.yourdomain.io

gateway:
  replicaCount: 1
  image:
    tag: *imageTag
  auth:
    selfURL: https://api.monoskope.yourdomain.io
    identityProviderURL: https://dex.yourdomain.io
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 1
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  backup:
    enabled: false

commandhandler:
  replicaCount: 1
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  # -- List of email addresses to identify superusers.
  superusers:
    []
    # - someone@yourdomain.io

queryhandler:
  replicaCount: 1
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  k8sAuthZ:
    # -- Enable external git repo reconciliation
    enabled: true
    # -- Configure secret provided as env vars
    # existingSecret: m8-k8sauthz
    config:
      # -- Configure repos
      repository:
        url: https://monoskope.io/test1.git
        caCert: this-is-a-ca-cert-in-pem
        authType: basic
        envPrefix: test1
      # -- Configure ClusterRole mapping
      mappings:
        - scope: CLUSTER
          role: admin
          clusterRole: cluster-admin
        - scope: TENANT
          role: oncall
          clusterRole: app-oncallee
      # -- Prefix used for users in clusters
      usernamePrefix: "m8-"
      subdir: test
      interval: 5m
      allClusters: true

ambassador:
  service:
    loadBalancerIP: 1.1.1.1 # IP address of your external load balancer
  metrics:
    serviceMonitor:
      enabled: true
      selector:
        release: monitoring

rabbitmq:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
