# Dev cluster environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - name: gitlab-registry

dex:
  enabled: true
  replicas: 3
  config:
    issuer: &issuer https://monoskope.dev.finleap.cloud/dex
    enablePasswordDB: false
    connectors:
      - type: gitlab
        id: gitlab-dev
        name: GitLab DEV
        config:
          baseURL: "https://gitlab.figo.systems"
          clientID: "{{ .gitlabClientId }}"
          clientSecret: "{{ .gitlabClientSecret }}"
          redirectURI: https://monoskope.dev.finleap.cloud/dex/callback
          groups:
            - "wolke7"
          use_login_as_id: false

cockroachdb:
  enabled: true
  statefulset:
    replicas: 5
  storage:
    persistentVolume:
      size: "1Gi"

rabbitmq:
  enabled: true
  replicaCount: 5

gateway:
  replicaCount: 3
  auth:
    issuerURL: *issuer
  ingress:
    enabled: true
    host: api.monoskope.dev.finleap.cloud

eventstore:
  replicaCount: 3
  enabled: true
  config:
    dbTlsSecret: monoskope-crdb-auth-evenstore
    busTlsSecret: monoskope-rabbitmq-auth-evenstore

ingress:
  enabled: true
  host: monoskope.dev.finleap.cloud
