# Dev cluster environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - name: gitlab-registry

hosting:
  issuer: letsencrypt-production
  domain: &domain monoskope.dev.finleap.cloud

cockroachdb:
  enabled: true
  statefulset:
    replicas: 5
  storage:
    persistentVolume:
      size: "1Gi"

rabbitmq:
  enabled: true
  replicaCount: 5

gateway:
  replicaCount: 2
  auth:
    issuerURL: https://gitlab.figo.systems
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 2
  enabled: true
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin
  storeDatabase:
    tlsSecret: monoskope-crdb-auth-evenstore
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  backup:
    enabled: true
    alerting:
      enabled: true
    schedule: "0 22 * * *"
    retentionCount: 7
    existingSecretName: eventstore-backup-credentials
    prometheusPushgatewayUrl: http://monitoring-prometheus-pushgateway.monitoring:9091
    destination:
      s3:
        endpoint: s3.es1.fra.optimist.innovo.cloud
        bucket: m8-eventstore-dev
        region: us-east-1

commandhandler:
  replicaCount: 2
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  superusers:
    # Enable superuser functionality to create initial admin rolebindings. Superusers can assign the system admin role
    # even if they don't have the system admin role themselves. This is needed to create admin users on initialization.
    enabled: true
    # List of email addresses to identify superusers.
    emails:
      - jan.steffen@finleap.com

queryhandler:
  replicaCount: 2
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin

ambassador:
  enabled: true
  replicaCount: 2
  service:
    loadBalancerIP: 31.13.187.241 # https://finleap-connect.atlassian.net/wiki/spaces/FCP/pages/1391153020/Development+IP+Addresses
