# Dev cluster environment values for monoskope.

global:
  imagePullSecrets:
    - name: gitlab-registry

vaultOperator:
  enabled: true
  basePath: app/{{ .Release.Namespace }}
  
hosting:
  issuer: letsencrypt-production
  domain: monoskope.dev.finleap.cloud

# cockroachdb:
  # dropExistingDatabase: true

gateway:
  replicaCount: 2
  auth:
    identityProviderName: gitlab
    identityProviderURL: https://gitlab.figo.systems
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  backup:
    enabled: false

commandhandler:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  # -- List of email addresses to identify superusers.
  superusers:
    - alexander.stielau@finleap.com
    - carolin.dohmen@finleap.com
    - christian.huening@finleap.com
    - jan.steffen@finleap.com
    - lukas.grundmann@finleap.com
    - lutz.behnke@finleap.com

queryhandler:
  replicaCount: 2
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

ambassador:
  replicaCount: 2
  service:
    loadBalancerIP: 31.13.187.241 # https://finleap-connect.atlassian.net/wiki/spaces/FCP/pages/1391153020/Development+IP+Addresses

cluster-bootstrap-reactor:
  replicaCount: 1
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
