# Dev cluster environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - name: gitlab-registry

cockroachdb:
  enabled: true
  statefulset:
    replicas: 5
  storage:
    persistentVolume:
      size: "1Gi"

rabbitmq:
  enabled: true
  replicaCount: 5

gateway:
  replicaCount: 3
  auth:
    issuerURL: https://gitlab.figo.systems
    clientID: "{{ .gitlabClientId }}"
    clientSecret: "{{ .gitlabClientSecret }}"
  ingress:
    enabled: true
    host: api.monoskope.dev.finleap.cloud
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 3
  enabled: true
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin
  storeDatabase:
    tlsSecret: monoskope-crdb-auth-evenstore
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

commandhandler:
  replicaCount: 3
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

queryhandler:
  replicaCount: 3
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin

ingress:
  enabled: true
  host: monoskope.dev.finleap.cloud
