# Dev cluster environment values for monoskope.

nameOverride: ""
fullnameOverride: ""

global:
  imagePullSecrets:
    - name: gitlab-registry

hosting:
  issuer: letsencrypt-production
  domain: &domain monoskope.dev.finleap.cloud

cockroachdb:
  enabled: true
  statefulset:
    replicas: 5
  storage:
    persistentVolume:
      size: "1Gi"

rabbitmq:
  enabled: true
  replicaCount: 5

gateway:
  replicaCount: 2
  auth:
    issuerURL: https://gitlab.figo.systems
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 2
  enabled: true
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin
  storeDatabase:
    tlsSecret: monoskope-crdb-auth-evenstore
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

commandhandler:
  replicaCount: 2
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

queryhandler:
  replicaCount: 2
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  messageBus:
    tlsSecret: monoskope-rabbitmq-auth-admin

ambassador:
  enabled: true
  replicaCount: 3
  service:
    loadBalancerIP: 31.13.187.241 # https://finleap-connect.atlassian.net/wiki/spaces/FCP/pages/1391153020/Development+IP+Addresses

# Configure ORY Oathkeeper
oathkeeper:
  enabled: true
  replicaCount: 2
  oathkeeper:
    config:
      authorizers:
        allow:
          enabled: true
      authenticators:
        jwt:
          enabled: true
          config:
            jwks_urls:
              - https://gitlab.figo.systems/oauth/discovery/keys
            scope_strategy: none
            trusted_issuers:
              - https://gitlab.figo.systems
            allowed_algorithms:
              - RS256
      mutators:
        noop:
          enabled: true
