# Copyright 2021 Monoskope Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dev cluster environment values for monoskope.

imageTag: &imageTag "0.0.1-local"

global:
  imagePullSecrets:
    - name: gitlab-registry

vaultOperator:
  enabled: true
  basePath: app/{{ .Release.Namespace }}/monoskope
  
hosting:
  issuer: letsencrypt-production
  domain: monoskope.dev.finleap.cloud

# cockroachdb:
  # dropExistingDatabase: true

gateway:
  replicaCount: 1
  image:
    tag: *imageTag
  auth:
    selfURL: https://api.monoskope.dev.finleap.cloud
    identityProviderName: gitlab
    identityProviderURL: https://gitlab.figo.systems
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

eventstore:
  replicaCount: 1
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  backup:
    enabled: false
    alerting:
      enabled: false
    schedule: "0 22 * * *"
    retentionCount: 7
    existingSecretName: m8-eventstore-backup-credentials
    prometheusPushgatewayUrl: http://monitoring-prometheus-pushgateway.monitoring:9091
    destination:
      s3:
        endpoint: s3.es1.fra.optimist.innovo.cloud
        bucket: devcluster-bkp
        region: us-east-1
    restore:
      enabled: false
      backupIdentifier: "monoskope/eventstore/2021-04-07T13:23:57Z-75131c3e-c4da-465f-8540-cb851cb8e4b0.tar"

commandhandler:
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  # -- List of email addresses to identify superusers.
  superusers:
    - alexander.stielau@finleap.com
    - carolin.dohmen@finleap.com
    - christian.huening@finleap.com
    - jan.steffen@finleap.com
    - lukas.grundmann@finleap.com
    - lutz.behnke@finleap.com

queryhandler:
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi

ambassador:
  deploy: false
  service:
    loadBalancerIP: 31.13.187.241 # https://finleap-connect.atlassian.net/wiki/spaces/FCP/pages/1391153020/Development+IP+Addresses

cluster-bootstrap-reactor:
  image:
    tag: *imageTag
  resources:
    limits:
      cpu: 2000m
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 64Mi
  issuerURL: https://api.monoskope.dev.finleap.cloud
