sequenceDiagram
    participant U as User
    participant K as kubectl
    participant C as Cluster
    participant A as Ambassador
    participant G as Gateway
    participant Q as QueryHandler
    participant I as Identity Provider
    U-->>+K: kubectl get nodes
    K-->>+C: calls get nodes
    C-->>+A: calls webhook
    A-->>+G: authenticate request
    G-->>+I: get user info with token
    I-->>-G: returns authorized
    G-->>+Q: check roles
    Q-->>-G: user is allowed to access cluster
    G-->>-A: returns authorized
    A-->>-C: returns authorized
    C-->>-K: returns response
    K-->>-U: shows nodes of cluster
