sequenceDiagram
    participant U as User
    participant M as monoctl
    participant G as Gateway
    participant D as Dex
    participant I as Identity Provider
    U-->>+M: monoctl command needing auth
    M-->>+G: calls API
    G-->>G: validates bearer token
    G-->>-M: returns that token has expired
    M-->>+G: calls RefreshAuth
    G-->>+D: get new id_token
    D-->>+I: get new id_token
    I-->>I: validates refresh_token
    I-->>-D: returns new id_token
    D-->>-G: returns id_token
    G-->>-M: returns id_token
    M-->>+G: calls API
    G-->>G: validates bearer token
    G-->>-M: returns API response
    M-->>-U: Output command response
