// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/finleap-connect/monoskope/pkg/api/gateway (interfaces: GatewayAuthZClient)

// Package gateway is a generated GoMock package.
package gateway

import (
	context "context"
	reflect "reflect"

	gateway "github.com/finleap-connect/monoskope/pkg/api/gateway"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGatewayAuthZClient is a mock of GatewayAuthZClient interface.
type MockGatewayAuthZClient struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayAuthZClientMockRecorder
}

// MockGatewayAuthZClientMockRecorder is the mock recorder for MockGatewayAuthZClient.
type MockGatewayAuthZClientMockRecorder struct {
	mock *MockGatewayAuthZClient
}

// NewMockGatewayAuthZClient creates a new mock instance.
func NewMockGatewayAuthZClient(ctrl *gomock.Controller) *MockGatewayAuthZClient {
	mock := &MockGatewayAuthZClient{ctrl: ctrl}
	mock.recorder = &MockGatewayAuthZClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayAuthZClient) EXPECT() *MockGatewayAuthZClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockGatewayAuthZClient) Check(arg0 context.Context, arg1 *gateway.CheckRequest, arg2 ...grpc.CallOption) (*gateway.CheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Check", varargs...)
	ret0, _ := ret[0].(*gateway.CheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockGatewayAuthZClientMockRecorder) Check(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGatewayAuthZClient)(nil).Check), varargs...)
}
