repositories:
  - url: https://monoskope.io/test1.git
    caCert: dGhpcy1pcy1hLWNhLWNlcnQ=
    basicAuth:
      username: test1
      password: testpw
    allClusters: true
    interval: 5m
  - url: https://monoskope.io/test2.git
    interval: 5m
    sshAuth:
      privateKeyPath: testkey.pem
      password: a25vd24taG9zdC1rZXlz
    clusters:
      - "dev"
      - "prod"
mappings:
  - scope: system
    role: admin
    clusterRoleName: cluster-admin
  - scope: tenant
    role: oncall
    clusterRoleName: app-oncallee
