repositories:
  - url: https://monoskope.io/test1.git
    branch: main
    caCert: dGhpcy1pcy1hLWNhLWNlcnQ=
    basicAuthPath: test_repo_one_basic_auth.yaml
    allClusters: true
    interval: 5m
  - url: https://monoskope.io/test2.git
    branch: test
    interval: 5m
    sshAuthPath: test_repo_two_ssh_auth.yaml
    clusters:
      - "dev"
      - "prod"
mappings:
  - scope: system
    role: admin
    clusterRoleName: cluster-admin
  - scope: tenant
    role: oncall
    clusterRoleName: app-oncallee
