repositories:
  - url: https://monoskope.io/test1.git
    caCert: dGhpcy1pcy1hLWNhLWNlcnQ=
    credentialsBasicAccessAuth:
      username: test1
      password: testpw
    allClusters: true
  - url: https://monoskope.io/test2.git
    sshAuth:
      identity: dGhpcy1pcy1hLXByaXZhdGUta2V5
      knownHosts: a25vd24taG9zdC1rZXlz
    clusters:
      - "dev"
      - "prod"
mappings:
  - scope: system
    role: admin
    clusterRoleName: cluster-admin
  - scope: tenant
    role: oncall
    clusterRoleName: app-oncallee
