// Copyright 2021 Monoskope Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: api/domain/common/roles.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Roles
type Role int32

const (
	// Admin role
	Role_admin Role = 0
	// User role
	Role_user Role = 1
	// OnCall role
	Role_oncall Role = 2
	// K8sOperator role
	Role_k8soperator Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "admin",
		1: "user",
		2: "oncall",
		3: "k8soperator",
	}
	Role_value = map[string]int32{
		"admin":       0,
		"user":        1,
		"oncall":      2,
		"k8soperator": 3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_domain_common_roles_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_domain_common_roles_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_domain_common_roles_proto_rawDescGZIP(), []int{0}
}

// Scopes
type Scope int32

const (
	// System scope
	Scope_system Scope = 0
	// Tenant scope
	Scope_tenant Scope = 1
	// Cluster scope
	Scope_cluster Scope = 2
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "system",
		1: "tenant",
		2: "cluster",
	}
	Scope_value = map[string]int32{
		"system":  0,
		"tenant":  1,
		"cluster": 2,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_api_domain_common_roles_proto_enumTypes[1].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_api_domain_common_roles_proto_enumTypes[1]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_api_domain_common_roles_proto_rawDescGZIP(), []int{1}
}

var File_api_domain_common_roles_proto protoreflect.FileDescriptor

var file_api_domain_common_roles_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x38, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x6e, 0x63, 0x61, 0x6c, 0x6c, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x6b, 0x38, 0x73, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x10,
	0x03, 0x2a, 0x2c, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69,
	0x6e, 0x6c, 0x65, 0x61, 0x70, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2f, 0x6d, 0x6f,
	0x6e, 0x6f, 0x73, 0x6b, 0x6f, 0x70, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_domain_common_roles_proto_rawDescOnce sync.Once
	file_api_domain_common_roles_proto_rawDescData = file_api_domain_common_roles_proto_rawDesc
)

func file_api_domain_common_roles_proto_rawDescGZIP() []byte {
	file_api_domain_common_roles_proto_rawDescOnce.Do(func() {
		file_api_domain_common_roles_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_domain_common_roles_proto_rawDescData)
	})
	return file_api_domain_common_roles_proto_rawDescData
}

var file_api_domain_common_roles_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_domain_common_roles_proto_goTypes = []interface{}{
	(Role)(0),  // 0: common.Role
	(Scope)(0), // 1: common.Scope
}
var file_api_domain_common_roles_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_domain_common_roles_proto_init() }
func file_api_domain_common_roles_proto_init() {
	if File_api_domain_common_roles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_domain_common_roles_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_domain_common_roles_proto_goTypes,
		DependencyIndexes: file_api_domain_common_roles_proto_depIdxs,
		EnumInfos:         file_api_domain_common_roles_proto_enumTypes,
	}.Build()
	File_api_domain_common_roles_proto = out.File
	file_api_domain_common_roles_proto_rawDesc = nil
	file_api_domain_common_roles_proto_goTypes = nil
	file_api_domain_common_roles_proto_depIdxs = nil
}
