name: OPA Tests

on:
  pull_request:
    paths:
      - '.github/workflows/opa.yaml' ## self-trigger
      - 'build/package/helm/gateway/files/*.rego'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Project
          uses: actions/checkout@v3
        - name: Test Open Policy Agent (OPA) Policies
          uses: finleap-connect/opa-test-action@v3.0.0
          with:
            tests: "build/package/helm/gateway/files/"
            options: "-v"
