name: OPA Tests

on:
  pull_request:
    paths:
      - '.github/workflows/opa.yaml' ## self-trigger
      - 'build/package/helm/gateway/files/*.rego'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Run OPA tests
          uses: petroprotsakh/opa-test-action@v2.1
          with:
            tests: "build/package/helm/gateway/files/policies/"
